### ISSUE TITLE
add list logos to result page

### ISSUE THREAD

**Issue by greemin** [felixfoertsch/mahlowat#9]

**Comment by greemin** [comment]
logo-buttons for the detail summary are implemented ... but the css does not do what it should do xD

**Comment by greemin** [comment]
for clean implementation logos with same size are required -> moved to backlog

**Comment by felixfoertsch** [comment]
Would be a nice addition for the "Übersicht" page instead of details view. 
```<img class='img-responsive' src='img/lists/$list_logo' title='$list_name_short Logo'>```
Todo: Make the vars available in elements.php

**Comment by greemin** [comment]
resolved with revision bdd9519
